name: CI SQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


env:
  DATABASE_HOST: 'sql234.main-hosting.eu'
  DATABASE_PORT: '3306'
  DATABASE_NAME: 'u463129590_github_actions'
  DATABASE_USERNAME: 'u463129590_github_actions'
  DATABASE_PASSWORD: 'Ns2b7bfqbf!'
  DATABASE_SCRIPT: 'script.sql'
 

jobs:
  Import_SQL:
    runs-on: ubuntu-latest
    name: MySQL Deploy Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Import SQL Script
        run: |
              mysql --host=$DATABASE_HOST --user=$DATABASE_USERNAME --password=$DATABASE_PASSWORD --database $DATABASE_NAME < $DATABASE_SCRIPT